### ISSUE TITLE
Status commands don't seem to work on the E5 3.4.46

### ISSUE THREAD

**Issue by NederBelg** [koalazak/dorita980#100]
Stop / pause / clean work fine

getTime / discovery / getMission not

var dorita980 = require('dorita980');
 
  var myRobotViaLocal = new dorita980.Local('xx', 'xxx', 'xxx.   ' );
 
  myRobotViaLocal.getMission()
  .then((mission) => {
    console.log(mission);
  }).catch((err) => {
    console.log(err);
  });

This seems to run for ever, no output. Do I something wrong?

the discovery sample script returns: undefined. Again do I something wrong?

**Comment by koalazak** [comment]
please update the library to `3.1.6` version and try getBasicMission() instead of getMission().
I also updated the documentation of getMission() method to explain why it doesn;t work on E5 robots.
thank you!
