### ISSUE TITLE
dock() after stop() is not executed

### ISSUE THREAD

**Issue by hokascha** [koalazak/dorita980#104]
I got an i7 and I'm trying to send it back to it's dock. So I'm using:
```
myRobotViaLocal.stop()
                .then(() => myRobotViaLocal.dock())
                .then(() => myRobotViaLocal.end())
                .catch(console.log);
```

The robot stops but then doesn't go back to it's homebase. Am I doing something wrong?

Calling `dock()` when the robot is not currently cleaning works as expected.

**Comment by thorazine-12** [comment]
I have the same problem - it is happening since recent iRobot firmware update. I know that because it worked properly few months ago.
If you will send second dock() command then robot will come back to its base.

**Comment by hokascha** [comment]
Sending a second `dock()` command right after the first doesn't work for me. What works is restarting the script, e.g. renewing the connection to the bot and then sending a `dock()` command.

**Comment by koalazak** [comment]
maybe it is a time issue? did you try to wait a second after the stop() to send the dock()?

**Comment by hokascha** [comment]
Your're right! Waiting for 10s between `stop()` and `dock()` works!

**Comment by warki** [comment]
During this period roomba is updating the map. I wait for a new state and then send the "dock" command.

**Comment by Mirarkitty** [comment]
You can either wait for "isReady" or until status that it's stopped is reported, I think. Then you can send "dock".
