### ISSUE TITLE
Some more commands for v2 firmware

### ISSUE THREAD

**Issue by kumy** [koalazak/dorita980#107]
While working on #106 I've found some other commands:

Topic | Payload | Comments
----- | ------- | --------
delta | `{ "state" : {"name": "My Cool Name"} }` | Define the robot name
cmd | `{ "command": "find", "time": 1579464963, "initiator": "localApp" }` | Locate the robot via emitting sound. The same command need to be sent a second time to stop sound.
delta | `{ "state" : { "mapUploadAllowed": false} }` | Enable/Disable map upload
cmd | `{ "command": "wipe", "time": 1579465092, "initiator": "localApp" }` | Factory reset the robot
delta | `{ "state" : { "language": 0 } }` | Set the robot language (1)
delta | `{ "state" : { "logUpload": true} }` | Upload robot logs. Where will it upload?
wifictl | `{ "get" : "discovery" }` | ???

(1) **Robot languages**
0 English
1 French
2 Spanish
3 Italian
4 Deutsch (Deutschland)
5 Russian
This match to the list from this message `{"state":{"reported":{"langs":[{"en-UK":0},{"fr-FR":1},{"es-ES":2},{"it-IT":3},{"de-DE":4},{"ru-RU":5}],"bbnav":{"aMtrack":54,"nGoodLmrks":13,"aGain":30,"aExpo":9},"bbpanic":{"panics":[8,9,8,8,1]},"bbpause":{"pauses":[17,3,0,3,3,13,14,13,0,13]}}}}`
Note: The app allow to download additional languages, so this list is not static

**Comment by koalazak** [comment]
refere to #107
