### ISSUE TITLE
Roomba 966 support?

### ISSUE THREAD

**Issue by Alcatr4zz** [koalazak/dorita980#11]
Is there a chance that this also works for the Roomba 966?

**Comment by koalazak** [comment]
I think yes. I didnt try, but should be work. 966 has the same features without Carpet Boost and other miniumin things. Can you try dorita980 on 966 and tell us what works and what not?

thanks!

**Comment by Jaghova** [comment]
Yes It works. I have a 966 and works perfectly

**Comment by koalazak** [comment]
cool!
