### ISSUE TITLE
Unable to get password

### ISSUE THREAD

**Issue by 3JL** [koalazak/dorita980#110]
Hi!
Weird question: I am unable to get a password, and yes I have read the other issues on this topic. But there is something stupid: the Roomba (980, firmware version 2.4.6-3) does not "play a series of tones". I have tried connecting at different moments during the cycle when continuously pressing the home button, but no success... Any clue what I may be doing wrong?
J

**Comment by jeremywillans** [comment]
This is the same process used to connect the roomba to your mobile app - such as from the [irobot faq](https://homesupport.irobot.com/app/answers/detail/a_id/17734/~/setting-up-your-wi-fi-connected-robot-with-the-irobot%C2%AE-home-app)

Perhaps try [resetting](https://homesupport.irobot.com/app/answers/detail/a_id/9087/~/how-do-i-reboot-my-robot-and-force-close-the-irobot%C2%AE-home-app%3F), and if that dosent work [factory resetting](https://homesupport.irobot.com/app/answers/detail/a_id/9047/~/why-factory-reset-your-robot-and-how-to-do-it%3F) your robot?

**Comment by 3JL** [comment]
Please forgive my stupidity... I have been pressing the Clean button, rather than the Home button :s
