### ISSUE TITLE
Dock state incorrect?

### ISSUE THREAD

**Issue by Zefau** [koalazak/dorita980#111]
The API delivers an entry `dock: { known: true }`. Is this the docking state of the Roomba (`true` = docked and `false` = not docked)?

I'm wondering because I get wrong values if this is supposed to be the docking state.

Thanks and kind regards

**Comment by koalazak** [comment]
no, It is not the docking state. It is true if the robot "knows" where is the dock. (I guess)

**Comment by Zefau** [comment]
Ah ok, is there a state though if the roomba is docked?

**Comment by jeremywillans** [comment]
“phase”:”charge” under cleanmissionstatus 👍
