### ISSUE TITLE
Smaller area

### ISSUE THREAD

**Issue by betolley** [koalazak/dorita980#113]
I have a iRobot 695 with wifi.  I can connect to it with no issue.  I have a smaller area near the kitty litter box I would like to have cleaned in the corner of the room a couple times a day.  I can start/stop/dock the system but is it possible to directly control the vacum around and only do that area?   Or possibly use .cleanRoom(args) and somehow setup a smaller area to clean?

**Comment by koalazak** [comment]
I think now this is possbile with the latest firmware. Take a look here https://github.com/koalazak/dorita980/issues/125
and  here: https://github.com/koalazak/dorita980#cleanroomargs
