### ISSUE TITLE
What do some of these do?

### ISSUE THREAD

**Issue by betolley** [koalazak/dorita980#114]
set Always Finish?  I have issues where I am trying to get the vacum to finish no mater what but it stops on my floor vents all the time.  Setting this didn't do anything for me.

Set Edge Clean?

**Comment by betolley** [comment]
Anyone that look at this the AlwaysFinish seems to continue cleaning if you are stopped with a error and tell it to clean again.  If I dont' set alwaysfinish it just makes a chime.

**Comment by drinfernoo** [comment]
Edge Clean makes it do a final pass near all the room edges as the last phase of the cleaning mission, as indicated in the iRobot app:
![image](https://user-images.githubusercontent.com/2319508/121024094-c1f46180-c758-11eb-9100-cb3cbf8045c7.png)
