### ISSUE TITLE
How do I setup a room?

### ISSUE THREAD

**Issue by Mannshoch** [koalazak/dorita980#116]
How do I setup a room?
Is it possible to Load different Room-settings?

**Comment by koalazak** [comment]
https://github.com/koalazak/dorita980/issues/125

**Comment by Mannshoch** [comment]
Do you have somwhere a tutorial how I could setup a zone/room?

**Comment by Mannshoch** [comment]
Is there a need to install the Roomba app for that?

**Comment by koalazak** [comment]
yes, the 5.0+ version ofthe Home app. And a compatible robot with "room cleaning" feature

**Comment by Mannshoch** [comment]
Hm, Google Play only have iRobot Home 4.8. Also I have a Roomba 980. It seems that this roboot do not have the Room cleaning feature. the firmware seems old. I'ts 2.4.6-3 from 2018-06-04 but it's the latest available Update.
The App was helpfull here. Thanks for your help.
