### ISSUE TITLE
Roomba i7 Error getting password

### ISSUE THREAD

**Issue by ddrees90** [koalazak/dorita980#124]
I've been attempting to retrieve the blid/password from my i7, but keep running into the same issue with the password. When I execute the package it returns all of the relevant data except for the password and provides the "Error getting password" response. On the i7 I am holding the home button until to roomba plays some tones and the center light turns blue and rotates. Below is the response I receive.

Robot Data:
{ ver: '3',
  hostname: 'Roomba-3175832471605730',
  robotname: 'Roomba',
  ip: '192.168.1.202',
  mac: 'D0:C5:D3:AE:96:08',
  sw: '3.5.62',
  sku: 'R690020',
  nc: 0,
  proto: 'mqtt',
  cap: { ota: 1, eco: 1, svcConf: 1 },
  blid: '3175832471605730' }
Error getting password. Follow the instructions and try again.

Any ideas why I am unable to obtain the password?

**Comment by tagno25** [comment]
I just purchased a second i7, and when it was put into pairing mode it would disconnect from the WiFi.

I would recommend pinging the Roomba's IP before putting it into pairing mode, if it is staying connected to the WiFi it should continue pinging.

I had to connect to the iRobot-******* network and get the password from 192.168.10.1

**Comment by koalazak** [comment]
@ddrees90 
- Are you sure you are pressing HOME button and not Clean?
- All your mobile apps are closed?
- Did you configure the roomba for first time with the mobile app? (if not, you need to do that)
- Reset the robot pressing Clean for 10 seconds aprox. Wait for restart and try again
- Are you in the same network?
- Try other version of node.js

**Comment by ddrees90** [comment]
Thanks for the responses @tagno25 and @koalazak. 

Per tagno's suggestion I pinged the Roomba and everything stayed connected while putting it into pairing mode, and no packet loss was experienced. I also tried connecting directly to the Roomba's network and running the command, but kept getting a ECONNREFUSED message.

@koalazak just responding to your suggestions below:

- yes, I am pressing the HOME button and not Clean. after holding the home button I get the tones and the blue light that circles around the CLEAN button.
- All of my mobile apps are closed (only have 1 connected and confirmed it was closed).
- I did configure the roomba via the mobile app
- I attempted the reset, and am still getting the same error
- I am on the same network
- I'm using the container (running on windows) so I'm just using the version of node packaged in that

**Comment by warki** [comment]
Is Roomba on the dock while you pressing the button?

**Comment by ddrees90** [comment]
yeah, the roomba is docked through the whole process

**Comment by ddrees90** [comment]
Ok, I just figured out the issue. For whatever reason there was a discrepancy between the IP address my router was listing for the Roomba, and what I ultimately found via the app. I reran the container with the address showed in the iRobot app and everything is now working. I'm not sure if the IP got reassigned during the reset that koalazak suggested (my router still doesn't show anything with that IP assigned) or if something is just getting lost.

**Comment by ddrees90** [comment]
Thanks everyone for trying to help, I really appreciate it!
