### ISSUE TITLE
Cleaning zone

### ISSUE THREAD

**Issue by warki** [koalazak/dorita980#125]
With the newest App Version 5.0.0 on, a new feature has been published: cleaning zone. Inside the app you can drag and drop a zone inside one or multiple rooms, which you want to be cleaned e.g. under the dining table. 

In my configurration the cleaning zone have its own user_pmapv_id, therefore you can not combine a zone cleaning task with a room cleaning task.

dorita980 and rest980 are able to perform this request already. 

To clean first the cleaning zone "Hallway entry" (Cleaning  Zone ID 5) and afterwards the Cleaning Zone "Dining Table" (Cleaning Zone ID: 0) zone 0, you can use the following method call:

```javascript
const args = {
  "ordered": 1,
  "pmap_id": "ABCDEFG123456FGKS789",
  "regions": [
    { "region_id": "5", "region_name": "Hallway entry", "region_type": "hallway", "type": "zid"},
    { "region_id": "0", "region_name": "Dining table", "region_type": "other", "type": "zid"}
  ],
  "user_pmapv_id": "190917T20125Z"
};

myRobotViaLocal.cleanRoom(args);
```

Happy cleaning to all

**Comment by koalazak** [comment]
PR merged. Thank you!
