### ISSUE TITLE
Will not work on Braava JetM6

### ISSUE THREAD

**Issue by Lypus4** [koalazak/dorita980#129]
Works great on Roomba (tx for that....), but not yet on Braava. 
Can detect blid, but not the password.
I have attached below the command return

-------------

[RobotData.txt](https://github.com/koalazak/dorita980/files/5610923/RobotData.txt)

**Comment by NickWaterton** [comment]
It does work on the Braava m6.
“Connection refused” means that another device is connected to the Braava, likely the app.

iRobot only allows one connection at a time to their devices.

Force close the app, and try again.

**Comment by Lypus4** [comment]
👍

**Comment by Lypus4** [comment]
🤜🤛
