### ISSUE TITLE
Usable without cloud services?

### ISSUE THREAD

**Issue by chrisspen** [koalazak/dorita980#130]
Can this library be used for controlling an i7+ Roomba without access to iRobot's cloud service?

I'm trying to find a way to initiate the Roomba's "clean all rooms" action in situations where I don't have WAN Internet access, or iRobot's cloud service is not accessible.

Your docs mention that this library can work over the your LAN, but does it still phone home to iRobot to control the Roomba?

**Comment by koalazak** [comment]
you don't need access to iRobot cloud services to use this library. Also you don't need iRobot home app. Check the readme.
