### ISSUE TITLE
Map and current region from current mission?

### ISSUE THREAD

**Issue by 1075dn** [koalazak/dorita980#131]
This package is AMAZING! Kudos!

Is there a way to get which map and region a robot is cleaning? (I know the iRobot HOME app can.)

Thanks so much for your help!

**Comment by koalazak** [comment]
It is not in `cleanMissionStatus` state object? (.getState())
Or emmited in mission event? Please, check that and confirm. Thank you!

**Comment by 1075dn** [comment]
Thanks so much for answering. I can't check yet because I have a new problem - when a robot hasn't been controlled remotely for a few days - does it stop responding to discovery/getRobotIP? I can't connect anymore... It's really weird, because I can control it now using the iRobot home app, but not dorita980. This happened to me again around two weeks ago, and then two days later it started responding again - I'm not sure why. Do you have any idea why this might happen? Thanks!

**Comment by mad73923** [comment]
> 
> 
> Thanks so much for answering. I can't check yet because I have a new problem - when a robot hasn't been controlled remotely for a few days - does it stop responding to discovery/getRobotIP? I can't connect anymore... It's really weird, because I can control it now using the iRobot home app, but not dorita980. This happened to me again around two weeks ago, and then two days later it started responding again - I'm not sure why. Do you have any idea why this might happen? Thanks!

Did you check if you have only one active connection (server or app)? The robot only supports 1 connection! This solved this issue for me.

**Comment by 1075dn** [comment]
I don't believe it was connected to anything else (I force closed the app). Maybe it was connected to the cloud? Does that count as a connection?

**Comment by mad73923** [comment]
I can't answer this, since I blocked every outgoing connection for my vacuum in my router firewall settings.

**Comment by 1075dn** [comment]
Hmm... I don't know if I could try that, as until my project is finished we regularly use the app...

**Comment by koalazak** [comment]
hello @1075dn,

can you test if the region is here? (reset your robot if it is not accepting connections please)

> It is not in `cleanMissionStatus` state object? (.getState())
> Or emmited in mission event? Please, check that and confirm. Thank you!
