### ISSUE TITLE
Mission status sqft no longer reported

### ISSUE THREAD

**Issue by drinfernoo** [koalazak/dorita980#137]
It appears that `sqft` is no longer updated by the robot in firmware 2.4.16-126. I have a Roomba 960, but am trying to find any statistic that could be used to get this from the robot.

**Comment by koalazak** [comment]
`sqft` is reported on my roomba980 with latest firmware `2.4.16-126` inside the `cleanMissionStatus` object.

**Comment by drinfernoo** [comment]
Is it updated? The field exists in my response, but never changes from `0`.

**Comment by koalazak** [comment]
you are rigth. it exist but always in 0.

**Comment by koalazak** [comment]
I see `bbrun.sqft` too but always in 3333 value. Maybe it is updated every X time. I did not leave the robot cleaning too much time to test this...let me know if `bbrun.sqft` works for you

**Comment by drinfernoo** [comment]
I believe that the `bbrun` fields are some type of "historical" data, probably lifetime or average values from the robot.

What initially tripped my suspicion (and led to me opening this issue) was that the Home Assistant integration no longer updated it's "area cleaned" (or "cleaning time") attribute(s). I used this package to analyze my response directly, and found that those two fields never update anymore.
