### ISSUE TITLE
No Data from iRobot Roomba 976

### ISSUE THREAD

**Issue by CKMartens** [koalazak/dorita980#151]
The software has not received any data from the Roomba for a few days. Control is also no longer possible.
The software version for the robot 2.4.16-126 is displayed in the iRobot App

**Comment by koalazak** [comment]
can you check with the latest dorita980 version please?

**Comment by koalazak** [comment]
@CKMartens any update on this?

**Comment by CKMartens** [comment]
It's partly working again. I can reconnect and control the iRobot, but the feedback is missing some values ​​such as the indication of the cleaned area. I think this could be due to changes at iRobot.

Thank you for your great work
