### ISSUE TITLE
Progress on j7+

### ISSUE THREAD

**Issue by farberm** [koalazak/dorita980#153]
I have obtained the blid and password with dorita980... but I cannot connect to the j7+ by using the homebridge-roomba2 plug-in.  Have you made any progress after your new purchase with any updates?

Thanks in advance.

**Comment by Danny2100** [comment]
I'm using home assistant and using the container to run dorito980. I got the blid and pw. How do I run the ```myRobot.getRobotState(waitForFields)``` as in what's the command that needs to coincide with that command when I enter it into the command line.

**Comment by bloomkd46** [comment]
I have someone with the same problem using [homebridge-iRobot issue#2](https://github.com/bloomkd46/homebridge-iRobot/issues/2) it immediately emits offline whenever you try to connect

**Comment by Danny2100** [comment]
I tried using rest980 but all I get is {} when I attempt to load the state and I know it's the right address as it actually has a Roomba logo and the addon in the logs shows the state was requested.

**Comment by CoreyJ87** [comment]
> I tried using rest980 but all I get is {} when I attempt to load the state and I know it's the right address as it actually has a Roomba logo and the addon in the logs shows the state was requested.

Do you have the official roomba integration installed? I had to disable that. They conflict

**Comment by Danny2100** [comment]
> > I tried using rest980 but all I get is {} when I attempt to load the state and I know it's the right address as it actually has a Roomba logo and the addon in the logs shows the state was requested.
> 
> Do you have the official roomba integration installed? I had to disable that. They conflict

It's disabled

**Comment by koalazak** [comment]
the state maybe empty {} in the first event and then start filling with data in subsecuent events

**Comment by Danny2100** [comment]
> the state maybe empty {} in the first event and then start filling with data in subsecuent events

For me the issue was the rest980 addon. It was updated now with support for the j7 and it works now.

**Comment by koalazak** [comment]
perfect
