### ISSUE TITLE
Unable to turn Roomba j7+ on/off

### ISSUE THREAD

**Issue by bloomkd46** [koalazak/dorita980#154]
Hello I am the owner of the [homebridge-iRobot](https://github.com/bloomkd46/homebridge-iRobot)  and I have an [issue](https://github.com/bloomkd46/homebridge-iRobot/issues/2) where after rebooting a j7+ you can get its state but you can’t toggle it on/off. Is this a known issue or a problem specific to their Roomba?

Thanks,
bloomkd46

**Comment by koalazak** [comment]
what do you mean with on/off? there is no on/off commands

**Comment by bloomkd46** [comment]
I mean clean/stop/dock

**Comment by koalazak** [comment]
latest dorita980 is working fine with j7+ robots (can clean/stop.dock properlly.
