### ISSUE TITLE
Found 0 robot(s)!

### ISSUE THREAD

**Issue by FredLiu0512** [koalazak/dorita980#162]
I have added them either in the iRobot mobile app or on the official website, but still can't find any robots.
What should I do next?
Where exactly should I add robots？
Please help me. Thank you.

**Comment by Utopiah** [comment]
Did you add the robot to the same WiFi network as the computer you are trying to use dorita980 on? If not make sure to do so first. After that, the robot will say so and display a WiFi symbol on it, use `nmap` to scan for devices and you should see a device from `AzureWave Technology`. If not then you are probably on different networks. Also make sure to disconnect from the app as only 1 connection is possible. You can turn WiFi off from your phone to be sure.

**Comment by heiybb** [comment]
> I have added them either in the iRobot mobile app or on the official website, but still can't find any robots. What should I do next? Where exactly should I add robots？ Please help me. Thank you.

Are you using the iRobot China Mainland version?
If so, seems that Chinese version firmware have a different configuration, and not compatible with repository.
