### ISSUE TITLE
How to get room updates

### ISSUE THREAD

**Issue by toddmo** [koalazak/dorita980#165]
Hello,

I got this working with i3.

I'd like to know how to get updates via events for the room changes. I read the readme and I'm still not sure how to do it. Thanks!

**Comment by zolakk** [comment]
It looks like latest firmwares don't report position on the local, maybe that information would be in the cloud (the app must get that somehow) but it seems the cloud connection development is on indefinite pause unfortunately

**Comment by PCjabber** [comment]
See #148 for more details
