### ISSUE TITLE
Is it Roomba 960 compatible?

### ISSUE THREAD

**Issue by PaulAnnekov** [koalazak/dorita980#17]
I'm gonna buy iRobot Roomba 960. Is this implementation compatible with it?

**Comment by iosdeveloper** [comment]
Probably all 900 series models (960, 966, 980), see https://github.com/koalazak/dorita980/issues/11 that are on firmware 1.6.6.

**Comment by PaulAnnekov** [comment]
10x

I will always use search before creating new issue
I will always use search before creating new issue
I will always use search before creating new issue
I will always use search before creating new issue
I will always use search before creating new issue

**Comment by MrMxyzptlk** [comment]
Yessssss!
