### ISSUE TITLE
How to block firmware updates?

### ISSUE THREAD

**Issue by soonerfan237** [koalazak/dorita980#173]
In the Advice section of README.md, it recommends blocking internet access to avoid OTA firmware updates. But I wasn't sure how best to do this.

Do I just totally block the device from connecting to my internet at the router? If so, will this block any other functionality of the Roomba?

Or do I need to specifically block only firmware updates? If so, how can I do this?

**Comment by koalazak** [comment]
block internet access to your robot from your router
