### ISSUE TITLE
Where I must install Dorita980 ?

### ISSUE THREAD

**Issue by Pm38110** [koalazak/dorita980#176]
Hello,
sorry I am a new user for Home Assistant.
Where I must install Dorita 980 ?
Into debian which host Home Assistant ?
or somewhere else ? In Docker ?
Could you explain me please ?
Thank you.

**Comment by koalazak** [comment]
hi @Pm38110,
dorita980 is not for direct installation in home assistant. This is a low-level library for developers. If you want to manage your Roomba from home assistant, you need to install a home assistant plugin that supports your robot (which most likely uses dorita980 underneath to communicate with the robot
