### ISSUE TITLE
Wake from local API?

### ISSUE THREAD

**Issue by iosdeveloper** [koalazak/dorita980#18]
Is anything available to enable the local API again after the robot has not been used for some time and is presumably sleeping? Wake from cloud API does not seem to work. The official app is able to do it, resulting in the lights turning on and a sound playing.

**Comment by maxbaeumle** [comment]
Aand mine is another victim of 2.0.0-34 :/

**Comment by iosdeveloper** [comment]
Aand mine just got another victim of 2.0.0-34 (this might explain why cloud wake API does not work) :/

**Comment by koalazak** [comment]
see #10
