### ISSUE TITLE
Roomba failed to connect

### ISSUE THREAD

**Issue by benmartucci** [koalazak/dorita980#180]
Ive retrieved the password and copied the string from => to <= and every time i do it it fails to connect, can someone please assist, Ive had this connected before doing these steps can't figure out where I'm going wrong.

Thnaks

> node ./bin/getPasswordCloud.js #######@gmail.com #########

Found 2 robot(s)!
Robot "#####" (sku: i455020 SoftwareVer: daredevil+2.4.7+daredevil-release+150):
BLID=> 92779472820C4AC2A0B99245D01ACBCE
Password=> :1:1685822905:IvmZzzrPp6YY9ptL <= Yes, all this string.

Robot "######" (sku: R675020 SoftwareVer: 3.5.62+95):
BLID=> 3173C30070409570
Password=> :1:1648399043:dbeKkZoBwstjPJPw <= Yes, all this string.

**Comment by benmartucci** [comment]
I am now getting this error when trying to retrieve the password, I reset the roomba to factory settings and re installed it. 

Error login into Gigya API.
{
  callId: 'e5d8369d08ff48dc9a581579663e925e',
  errorCode: 400093,
  errorDetails: 'Missing required parameter: ApiKey',
  errorMessage: 'Invalid ApiKey parameter',
  apiVersion: 2,
  statusCode: 400,
  statusReason: 'Bad Request',
  time: '2023-08-10T12:47:23.429Z'

**Comment by rahmanonik18** [comment]
Anyhow you re sending the appID while you're doing this? Try to change the appID, it may work

**Comment by benmartucci** [comment]
I actually got it working today, using the Dortia980 off github to obtain the password. I acutely waited until HA found the roomba after startup, not pressing the buttons, configure it, wait until it asked for the password. Copy and paste, and that seem to do the trick. I am currently running Home Assistant to this configuration. 
Home Assistant 2023.8.3
Supervisor 2023.08.1
Operating System 10.5
Frontend 20230802.1 - latest
