### ISSUE TITLE
Can't connect to get password. Says API Key required. 

### ISSUE THREAD

**Issue by h00pak** [koalazak/dorita980#189]
Using get-roomy-password <ip address> gives result of unsafe legacy negotiation disabled and trying to get-roomy-password-cloud <login> <password> is now saying that the API Key is required.

Any way around these? How does one get an API Key?

$ get-roomba-password-cloud h00pak@testemail.com Password!!##
Error login into Gigya API.
{
  callId: '6b01ee3c5cd0490288f2950141efefaa',
  errorCode: 400093,
  errorDetails: 'Missing required parameter: ApiKey',
  errorMessage: 'Invalid ApiKey parameter',
  apiVersion: 2,
  statusCode: 400,
  statusReason: 'Bad Request',
  time: '2024-03-17T19:25:11.414Z'
}

**Comment by kkaminski7** [comment]
I am experiencing exactly the same the same issue.

**Comment by h00pak** [comment]
For me, this ended up being a problem with two special characters in a row at the end of my password. I was using the Nick Waterton solution and finally changed the password on a guess. Immediately returned all the data. On Mar 24, 2024, at 8:13 AM, kkaminski7 ***@***.***> wrote:﻿
I am experiencing exactly the same the same issue.

**Comment by kkaminski7** [comment]
Thank You h00pak for update on Your situation. It seems like we had the same issue, I have changed password to more human readable form and it works for me now aswell.
