### ISSUE TITLE
Issues using Docker

### ISSUE THREAD

**Issue by ScenicSystemsLLC** [koalazak/dorita980#190]
I am going to start by saying I don't really think this is an issue with this package but my own ignorance, but I need a couple of questions answered.

I am running Home Assistant on an ODROID-N@ Platform as an appliance.
That being the case I cannot run docker on the appliance.

I have an Ubuntu server with Docker and Dorita980 installed that I can access and retrieve room information from my Roomba.
However, from HA I am unable to connect to my Linux machine over the network to access docker.

I am new to Docker and HA so I have 2 questions.
The first given my Home Assistant installation is the use of this package an option. 
The second would then be if it is how do I go about configuring Home Assistant to use this?

My Linus machine and Home Assistant appliance are on the same local network.

Thank you for any feedback you can give.

**Comment by koalazak** [comment]
hi @ScenicSystemsLLC 
you don't need to intall dorita980 or rest980 on your own. This is a library for developers.
If you want to control your robot with HA, just install HA and then a plugin for your robot (those pplugis probabily will use dorita980 internally, but yoy don't need to worry about installation).

regarding Home Assistant, I don't know, you should ask on their forums.

regards
