### ISSUE TITLE
OK, I have update my json to 3.0.0 and then NPM update but no go

### ISSUE THREAD

**Issue by MrMxyzptlk** [koalazak/dorita980#20]
I created a myapp.js and filled it with: what it shows on your main page in github.
when I run ./myapp.json it complains about the first line where it include the dorita980 library?

Where do I put the myapp.js?
I did put my BLID and password which worked in my pre-2.0 firmware with you previous versions?

**Comment by koalazak** [comment]
You have node.js installed? if not, install node.js in your system.

Put your myapp.js file in an empty directory.
Then you need to set dorita980 as dependecy of your project ( your project is myapp.js).
Do do that you need to run `npm install dorita980 --save` in the same directory that you have the myapp.js file.
Note that a `node_modules` directory and `package.json` files was created.
- node_modules store all the node.js libraries installed by you.
- package.json define some metadata for your project. Including your dependencies (dorita980 is a dependecy in your project)

Then run your app with the `node myapp.js` command.

Yes, use the blid and password you get in old version.

**Comment by MrMxyzptlk** [comment]
Danke!

**Comment by MrMxyzptlk** [comment]
So I decided to start from scratch.

I deleted my old dorita980 directory.

I created a myapp.js in a new empty directory.

I ran the command npm install dorita980 --save in the same directory with the myapp.js

I ran the command node myapp.js

Nothing happened, there was just a blank line while the application ran.

I also changed the myapp.js to find my roomba; I already know the IP but I was just seeing if I could get anything to work.

When I ran the command node myapp.js it just sat there indefinitely saying searching for robots.

I'm obviously a complete newb when it comes to MQTT and Node. What am I doing wrong?

**Comment by MrMxyzptlk** [comment]
OK, I figured out my issue. It was a me node fully understanding how node works issue.
Thanks.

**Comment by MrMxyzptlk** [comment]
I just did a new install of Linux I have node npm and all is well but when I run npm dorita980 --save in the same empty directory other than myapp.js this is the error I get?

npm WARN enoent ENOENT: no such file or directory, open '/home/anthony/git/package.json'
npm WARN git No description
npm WARN git No repository field.
npm WARN git No README data
npm WARN git No license field.

**Comment by koalazak** [comment]
`npm dorita980 --save` ???
should be `npm install dorita980 --save`

**Comment by MrMxyzptlk** [comment]
Yes that is what I meant...sorry!

npm install dorita980 --save

**Comment by koalazak** [comment]
there a warnings cos you dont have a previus package.json created. ignore them

**Comment by MrMxyzptlk** [comment]
Got it...OK all is well again.

**Comment by Seidlm** [comment]
@MrMxyzptlk can you explain what you did with node to get the myapp running, got the same like you, starting myapp is an empty line
