### ISSUE TITLE
2 Robots (980) same network

### ISSUE THREAD

**Issue by steedferns** [koalazak/dorita980#22]
I created a homebridge (homekit) plugin. It works fine for 1 robot at a time. The second robot returns { ok:null } but never starts . Anyone know why this would happen?

**Comment by koalazak** [comment]
I dont have 2 robots to try and I dont kwno how homebridge works
no idea :/

**Comment by koalazak** [comment]
If you use the dorita980 example snippet doplicated to send commands to 2 robots. that works?

**Comment by koalazak** [comment]
can you share that code?

**Comment by steedferns** [comment]
I run the code below twice for each robot.  (Not in the same program!) 

The both return ok, but the second does not start.

`
var dorita980 = require('dorita980');

var myRobotViaLocal = new dorita980.Local('id', 'password', 'ip'); // robot IP address

myRobotViaLocal.on('connect', function () {
// start!
myRobotViaLocal.start().then(() => {
myRobotViaLocal.end(); // disconnect to leave free the channel for the mobile app.
}).catch((err) => {
console.log(err);
});
});
`

**Comment by JensBonse** [comment]
Are both robots on firmware 2.0.0-34?
Sounds like the old cloud api. It still answers like expected but does not trigger the robot.

**Comment by steedferns** [comment]
Yes, both are the same firmware.  I can only get robot 2 to work if the other is "inactive/sleeping"? Its a hit or miss

**Comment by koalazak** [comment]
maybe the robots talk with each others when an action is performed? and the channel is occuped.
Have you the mobile app offline?
Can you send commands at the same time with 2 mobile apps to the robots?

**Comment by steedferns** [comment]
Yes, I can send commands at the same time using the app.

**Comment by koalazak** [comment]
news?

**Comment by koalazak** [comment]
reopen if needed

**Comment by blaster2014** [comment]
Have two 980 on the same network and when both are running at the same time they both don't complete the job.  One will work for an hour and return back to base as complete.  In fact only 1/3 of the home has been completed.
