### ISSUE TITLE
Will not return to prompt

### ISSUE THREAD

**Issue by akwak2015** [koalazak/dorita980#23]
Hi,
On my system the examles will stay on a loop. For example:
var myRobotViaLocal = new dorita980.Local('xxxxxxxxxxxxxx', 'yyyyyyyyyyyyyy', '192.168.168.28'); // robot IP address

myRobotViaLocal.on('connect', function () {
  myRobotViaLocal.getWeek().then((weekConfig) => {
    console.log(weekConfig)
    myRobotViaLocal.end(); // disconnect to leave free the channel for the mobile app.
  }).catch((err) => {
    console.log(err);
  });
});

udo@NodeJS:~/iRobot$ node getShedule.js
{ cycle: [ 'none', 'start', 'none', 'start', 'start', 'none', 'start' ],
  h: [ 9, 9, 9, 9, 9, 9, 9 ],
  m: [ 0, 0, 0, 0, 0, 0, 0 ] }

But I will not get my prompt. I have to press strg+c to get back to console.

Ist this normal?

Im using node v6.9.5 on "Ubuntu 16.04.2 LTS"

Regards

**Comment by koalazak** [comment]
update dorita980, its a fixed bug
