### ISSUE TITLE
Error: connect ECONNREFUSED

### ISSUE THREAD

**Issue by pgattu** [koalazak/dorita980#26]
I am running the getpassword script and getting the following error.  See below for version numbers and complete script output.  As you can see from the script output, some information has been gathered from the Roomba, while it encountered an error before it was able to read the password.  I have Roomba 980.

Error: connect ECONNREFUSED 192.168.1.241:8883
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)

**Here are the version numbers:**

C:\temp\dorita980-master>node -v
v6.9.5

C:\temp\dorita980-master>npm -v
3.10.10

**Here's the output of the script:**

C:\temp\dorita980-master>npm run getpassword 192.168.1.241

> dorita980@3.0.6 getpassword C:\temp\dorita980-master
> node ./bin/getpassword.js "192.168.1.241"

Make sure your robot is on the Home Base and powered on (green lights on). Then press and hold the HOME button on your robot until it plays a series of tones (about 2 seconds). Release the button and your robot will flash WIFI light.
Then press any key here...
Looking for robots...
Robot found! with blid/username: 3117050062127620
{ ver: '2',
  hostname: 'Roomba-3117050062127620',
  robotname: 'Roomba 1',
  ip: '192.168.1.241',
  mac: 'F0:03:8C:1E:32:AF',
  sw: 'v1.6.4',
  sku: 'R980020',
  nc: 0,
  proto: 'http' }
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 192.168.1.241:8883
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "getpassword" "192.168.1.241"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! dorita980@3.0.6 getpassword: `node ./bin/getpassword.js "192.168.1.241"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dorita980@3.0.6 getpassword script 'node ./bin/getpassword.js "192.168.1.241"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the dorita980 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/getpassword.js "192.168.1.241"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs dorita980
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls dorita980
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\temp\dorita980-master\npm-debug.log

C:\temp\dorita980-master>

**Comment by koalazak** [comment]
As you can see in that output, your robot has firmware 1.6.4 and use http protocol.
Check the readme for firmware 1.6.6 to get your password and use dorita
