### ISSUE TITLE
new firmware v2.2.5-2

### ISSUE THREAD

**Issue by koalazak** [koalazak/dorita980#31]
getpassword works, state events and cleaning preferences too.
commands like start/stop/dock doesnt work :/
next week i will try to fix

soundVer: '31'
uiSwVer: '4582'
navSwVer: '01.09.09' >> '01.11.02'
wifiSwVer: '20902' >> '20923'
mobilityVer: '5309' >> '5420'
bootloaderVer: '3580',
umiVer: '5' >> '6'
softwareVer: 'v2.0.0-34' >> 'v2.2.5-2'
svcEndpoints.svcDeplId: 'v005' >> 'v007'

and a new creepy property in the state: `mapUploadAllowed: true`
disable with: `myRobotViaLocal.setPreferences({mapUploadAllowed: false})` :trollface:

**Comment by iosdeveloper** [comment]
Start/stop/dock work for me in v2.2.5-2. ¯\_(ツ)_/¯

**Comment by koalazak** [comment]
its true, works for me now ¯_(ツ)_/¯

**Comment by letier** [comment]
That's great news. My roomba didn't upgrade, yet.

**Comment by koalazak** [comment]
I will update the README to encorage poeple to block their roomba internet connection if enjoy dorita980 to avoid the updates until know if dorita980 still works...

**Comment by Mandy2000** [comment]
well, for me it works SOMETIMES ... tried it TODAY with my Roomba 960 ... works in about 50% of the cases only

**Comment by BladeZX9123** [comment]
Is there a way to get back the history from the app of the successful runs?

**Comment by koalazak** [comment]
the history is gone cos you block the internet connection and the robot cant send the information.
I dont know if allowing the internet connection now, the robot send the old history. I dont think so.

The final solution is blocking only the urls used to update the firmware and allow the rest. ( I dont know wich they are)
