### ISSUE TITLE
Issue getting password

### ISSUE THREAD

**Issue by eddiezab** [koalazak/dorita980#34]
I have 2 980's, both with the 2.2.5-2 firmware. Attempting to get the password pulls the Robot Data, but I obtain a message: "Error getting password. Follow the instructions and try again."

I've tried multiple times on both Roombas to no avail. Is there something I can do to debug, or obtain the password via alternative means?

**Comment by koalazak** [comment]
node version? close your mobile app. share the output.

**Comment by eddiezab** [comment]
It was the node version (running Debian Sid, version was 5.0). Upgraded to 7.7.1, works as expected. Thanks for the quick response and awesome library!
