### ISSUE TITLE
My Roomba 980 can't automatic update firmware 2.0

### ISSUE THREAD

**Issue by saclo** [koalazak/dorita980#35]
Hello
My Roomba 980 still firmware 1.6.6 . Who can help me how to  update to firmware 2.0 . i'm waiting about 3 month and don't see anything .
Thank you

**Comment by koalazak** [comment]
Are you sure your roomba has internet connection?
To check that verify if you see the recent history, or if you can control your robot with the official app when you are not in home.

If the robot has internet connection OK, try a soft reset: (hold CLEAN button for 10 seconds until the sound). And wait a few days more.

**Comment by saclo** [comment]
i sure , my roomba has internet connection . i have reset many time but nothing .
Please help me .

**Comment by Anderman** [comment]
@saclo Did you solve the problem. My robot 980 is stil on 1.6.4
