### ISSUE TITLE
V2.2.5-2 looks like they broke it again

### ISSUE THREAD

**Issue by sheppy99** [koalazak/dorita980#36]
My Roomba has had its firmware upgraded again and dorita980 seems broken. Also the app seems to only connect via the net now, running node to query it just gives an empty reply, and ports 1883 and 1883 appear closed.
Knew I should have bought a different make with an open APi!!

**Comment by koalazak** [comment]
According to https://github.com/koalazak/dorita980/issues/31 dorita980 stills works.
If you has the official app open, then dorita980 cant connecto to the robot. Close all other conections, soft reset the robot (10 seconds CLEAN button) and try again.

**Comment by sheppy99** [comment]
Is this locally or via the cloud?

Sent from my iPhone

On 14/03/2017, at 4:08 AM, Facu ZAK <notifications@github.com<mailto:notifications@github.com>> wrote:


According to #31<https://github.com/koalazak/dorita980/issues/31> dorita980 stills works.
If you has the official app open, then dorita980 cant connecto to the robot. Close all other conections, soft reset the robot (10 seconds CLEAN button) and try again.

**Comment by koalazak** [comment]
locally. Cloud api does not work yet with 2.x.x.

**Comment by sheppy99** [comment]
That worked - what's the easiest way of stopping these clowns from updating it again?

**Comment by koalazak** [comment]
If you block the internet connectio to your robot then, the history will not be available and you can not control the robot from outside your home.

**Comment by sheppy99** [comment]
Given that with the new firmware. the robot seems to shutdown its local comms the moment the app has connected, the apps not really usable now anyway if I want to use the APi with my home automation, so nothing more is lost with blocking it. 
I much preferred it before they started meddling!
