### ISSUE TITLE
Including the Express framework to make a REST interface

### ISSUE THREAD

**Issue by roelbroersma** [koalazak/dorita980#4]
Hello,

(first of all, sorry if this is not the way to communicate but I couldn't find a way to create feature request or stat a dicussion)

Dorita980 is great! but it is hard to integrate for a lot of domotic frameworks, why?  Because you MUST have the node.js environment available on your domotic platform and able to control it (execute the functions).

It would be much easier and better when this had a REST interface.  In that case you can even run it 'as a server' on your Synology, which has node.js implemented as a package.

If it's a rest interface, you can easily call something like: "http://my-synology:3000/dorita980?action=do_start"

Via the express framework it's easy to create the route's (all the functions).
A static download path for the image: "http://my-synology:3000/dorita980/image.gif or svg" is perfect for domotics, you can then show the actual image on your visualisation/touchscreens. (almost every domotica solution has a way to update/reload an image every x seconds).

Can we start a discussion on how to implement this, what is the best way...etc.?

(for people not familiar with the Express framework, check this: http://blog.modulus.io/nodejs-and-express-create-rest-api )

**Comment by koalazak** [comment]
Hi @roelbroersma, 
I think that is a great idea!
I just create https://github.com/koalazak/rest980 project to make this real.
All local methods in dorita980 are already mapped to this REST express server. Check this out!
Full documentation and cloud methos pending...but what you think?

closing this thread, following on `rest980` :)

best regards,
