### ISSUE TITLE
I can't get the password

### ISSUE THREAD

**Issue by ianfas** [koalazak/dorita980#41]
When I run: nodejs ./bin/getpassword.js x.x.x.x
I get the following error:
Error getting password. Follow the instructions and try again.
The blid is returned but the password return data is 0.
Do you have any tips?
I have firmware:   sw: 'v2.2.5-2',
Thanks

**Comment by koalazak** [comment]
take a look at this closed issues: 
https://github.com/koalazak/dorita980/issues/34
https://github.com/koalazak/dorita980/issues/27
https://github.com/koalazak/dorita980/issues/21
https://github.com/koalazak/dorita980/issues/19
