### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by B4RD4k** [koalazak/dorita980#42]
Just want to ask if somebody here has download the firmware of IROBOT ?

**Comment by JensBonse** [comment]
As far as I know no one did. There firmware is only downloaded by the robot. So we even do not know the URL AFAIK.

**Comment by koalazak** [comment]
nope.
You can [play with the undocument](https://github.com/koalazak/dorita980#publish) commands: `dlkpg`, `patch` and with the states `manualUpdate`, `softwareVersion`, `swUpdateAvailable` and try to get the firmware URL.

**Comment by iosdeveloper** [comment]
FWIW, I saw a firmware in the iOS app bundle.

**Comment by B4rD4k** [comment]
Great, 10x guys.. i will update if i find sth.
