### ISSUE TITLE
Info on new python interpretation of dorita980

### ISSUE THREAD

**Issue by NickWaterton** [koalazak/dorita980#47]
If anyone is interested, I have just uploaded my interpretation of dorita980 in python 2.7.

It's not the same as dorita980, but covers much the same ground. Provides two python classes for manipulating the Roomba 980. Assuming a future FW upgrade doesn't break things.

Thanks to all the good work figuring out how the Roomba works done here!

Check it out here:
[https://github.com/NickWaterton/Roomba980-Python](url)

**Comment by pschmitt** [comment]
Thanks, nice work. The link is broken though: https://github.com/NickWaterton/Roomba980-Python

**Comment by koalazak** [comment]
nice! thanks for sharing!
