### ISSUE TITLE
Control movement?

### ISSUE THREAD

**Issue by just99** [koalazak/dorita980#49]
Hi!
Is it possible to control the movement of the Roomba? Turn left, move forward, etc.

**Comment by koalazak** [comment]
I dont know if the robot support that via API. But if the robot support that, then dorita980 is already supporting that with the `myRobot.publish()` method.
Maybe sending a new state with changes in the X,Y mission position object you can move your robot to that specific point.

**Comment by just99** [comment]
Developer answer: _The Roomba 980 has an integrated navigation system which helps it move around clutter and small gaps. This system is a part of the Roomba's API which is currently closed._
