### ISSUE TITLE
Brand new 690 Firmware ( 3.2.7+26 )

### ISSUE THREAD

**Issue by Norien** [koalazak/dorita980#56]
Just picked up a brand new 690 and I’m having a hell of a time getting my Id and password.
Is there any chance for support for newer firmware?

**Comment by koalazak** [comment]
Hi,
If my 980 eventualy updated the firmware, I will update dorita980 to support the new firmware.
But at the moment my 980 has v2.2.11-4

**Comment by koalazak** [comment]
there is not firmware v3 for 900 series.
https://homesupport.irobot.com/app/answers/detail/a_id/529/p/4116

**Comment by Norien** [comment]
This is from my iRobot app, I assumed that was the firmware version. If not where can I find the correct version?

![capture _2017-10-20-08-31-24](https://user-images.githubusercontent.com/8930713/31820907-485aa9c6-b571-11e7-9007-6c72d9ed4d2d.png)

**Comment by koalazak** [comment]
yes, 690 has a completly diferent firmware (v3.x.x) that 900 series (2.x.x).
So, dorita980 is not going to upgrade to be compatible with other firmwares that are not of the 800/900 series.

**Comment by Norien** [comment]
I'm considering exchanging my 960 for a 980 so this may just push me to do so. Thank you for your time.
