### ISSUE TITLE
Cleaning by zone.

### ISSUE THREAD

**Issue by petkov** [koalazak/dorita980#57]
Hi,

I was looking for a way to program Roomba to clean only part of a house and haven’t found any. 900 series model can map a house. So it should be possible to select a zone (eg.: kitchen or living room) on the map and ask roomba to clean just that area.

Is this possible to do using this framework?

Regards,
Alexey

**Comment by koalazak** [comment]
nop, I dont know a way to send the roomba to a x,y point, yet.
