### ISSUE TITLE
getpassword failing on one of my Roomba 980s

### ISSUE THREAD

**Issue by aalcock** [koalazak/dorita980#64]
I have used getpassword on my fleet of 3 Roomba 980s (all updated to the latest firmware). getpassword worked flawlessly on two, but failed on the third:

> ktboundary:dorita980 aalcock$ npm run getpassword 192.168.86.10
> 
> > dorita980@3.0.12 getpassword /Users/aalcock/dorita980
> > node ./bin/getpassword.js "192.168.86.10"
> 
> Make sure your robot is on the Home Base and powered on (green lights on). Then press and hold the HOME button on your robot until it plays a series of tones (about 2 seconds). Release the button and your robot will flash WIFI light.
> Then press any key here...
> events.js:165
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: connect ECONNREFUSED 192.168.86.10:8883
>     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1170:14)
> Emitted 'error' event at:
>     at emitErrorNT (internal/streams/destroy.js:64:8)
>     at process._tickCallback (internal/process/next_tick.js:114:19)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! dorita980@3.0.12 getpassword: `node ./bin/getpassword.js "192.168.86.10"`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the dorita980@3.0.12 getpassword script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/aalcock/.npm/_logs/2018-03-13T15_40_41_676Z-debug.log

The log file referenced above is shown below:

> 0 info it worked if it ends with ok
> 1 verbose cli [ '/usr/local/Cellar/node/9.8.0/bin/node',
> 1 verbose cli   '/usr/local/bin/npm',
> 1 verbose cli   'run',
> 1 verbose cli   'getpassword',
> 1 verbose cli   '192.168.86.10' ]
> 2 info using npm@5.6.0
> 3 info using node@v9.8.0
> 4 verbose run-script [ 'pregetpassword', 'getpassword', 'postgetpassword' ]
> 5 info lifecycle dorita980@3.0.12~pregetpassword: dorita980@3.0.12
> 6 info lifecycle dorita980@3.0.12~getpassword: dorita980@3.0.12
> 7 verbose lifecycle dorita980@3.0.12~getpassword: unsafe-perm in lifecycle true
> 8 verbose lifecycle dorita980@3.0.12~getpassword: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/aalcock/dorita980/node_modules/.bin:/Users/aalcock/bin:/Users/aalcock/Development/Libraries/android-sdk-macosx/tools:/Users/aalcock/Development/Libraries/android-sdk-macosx/platform-tools:/usr/local/sbin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Applications/Server.app/Contents/ServerRoot/usr/bin:/Applications/Server.app/Contents/ServerRoot/usr/sbin:/Users/aalcock/Development/Libraries/android-ndk-r8e:/Users/aalcock/Development/Libraries/apache-maven-3.0.5/bin:/Users/aalcock/Development/Libraries/gradle-1.6/bin
> 9 verbose lifecycle dorita980@3.0.12~getpassword: CWD: /Users/aalcock/dorita980
> 10 silly lifecycle dorita980@3.0.12~getpassword: Args: [ '-c', 'node ./bin/getpassword.js "192.168.86.10"' ]
> 11 silly lifecycle dorita980@3.0.12~getpassword: Returned: code: 1  signal: null
> 12 info lifecycle dorita980@3.0.12~getpassword: Failed to exec getpassword script
> 13 verbose stack Error: dorita980@3.0.12 getpassword: `node ./bin/getpassword.js "192.168.86.10"`
> 13 verbose stack Exit status 1
> 13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
> 13 verbose stack     at EventEmitter.emit (events.js:180:13)
> 13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
> 13 verbose stack     at ChildProcess.emit (events.js:180:13)
> 13 verbose stack     at maybeClose (internal/child_process.js:936:16)
> 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
> 14 verbose pkgid dorita980@3.0.12
> 15 verbose cwd /Users/aalcock/dorita980
> 16 verbose Darwin 17.4.0
> 17 verbose argv "/usr/local/Cellar/node/9.8.0/bin/node" "/usr/local/bin/npm" "run" "getpassword" "192.168.86.10"
> 18 verbose node v9.8.0
> 19 verbose npm  v5.6.0
> 20 error code ELIFECYCLE
> 21 error errno 1
> 22 error dorita980@3.0.12 getpassword: `node ./bin/getpassword.js "192.168.86.10"`
> 22 error Exit status 1
> 23 error Failed at the dorita980@3.0.12 getpassword script.
> 23 error This is probably not a problem with npm. There is likely additional logging output above.
> 24 verbose exit [ 1, true ]

**Comment by koalazak** [comment]
restart your robot, close all other clients (like mobile app) and try again. (review other issues with the same problem before open a new issue, thanks)
