### ISSUE TITLE
Set robot position?

### ISSUE THREAD

**Issue by mnowotka** [koalazak/dorita980#68]
Hi,

Thanks for this great project! Probably Roomba API doens't expose such method, but I wanted to ask just to make sure. Is it possible to ask the robot to go to a specified point on the map? To me, this is the biggest lack in functionality of the official app and it would be great to tell robot to go to some specific point in room and start cleaning there.

**Comment by koalazak** [comment]
You can experiment with `myRobot.publish()` method. 
Dupicated #49 (and #67,#49, #57 ¬¬)

**Comment by elgalu** [comment]
Did someone managed to use `myRobot.publish()` to move the robot to arbitrary positions or left/right/forward/back ?
