### ISSUE TITLE
Version 3

### ISSUE THREAD

**Issue by sciurius** [koalazak/dorita980#84]
My brand new e5 comes with software version 3.4.42-71.
Can I still use dorita980?
Most of the functionality seems to work (getting password, retrieve / set information).
But in particular the getSys() fails (doesn't return). And I cannot get a map using rest980...

**Comment by koalazak** [comment]
Hi, yes you can. But e5 model does not report the position so you can't map.
Regarding getSys() and other methods that dont return data on your model, you can replace they with [getRobotState()](https://github.com/koalazak/dorita980/issues/81#issuecomment-483458691)
