### ISSUE TITLE
Additional i7 Commands

### ISSUE THREAD

**Issue by briandlucas** [koalazak/dorita980#85]
found a few additional i7 commands:
"train" - starts a smart maps training run
"evac" - i7+ empty bin
"clean" - seems to be the same as "start" but unclear

also, i7 seems to be more particular about time parameter where other models don't seem to care

**Comment by koalazak** [comment]
hey @briandlucas how are you?
I just added `train` and `evan` commands on `dorita980@3.1.3`. Can you please test it? I dont own a i7 robot :/
Please try the commands on same circumstances would you try from the mobile app (maybe evac() only works if the bin is full or something like that)


```javascript
var dorita980 = require('dorita980');

var myRobotViaLocal = new dorita980.Local('MyUsernameBlid', 'MyPassword', '192.168.1.104');

myRobotViaLocal.on('connect', init);

function init () {
  myRobotViaLocal.evac()
  .then(() => myRobotViaLocal.end()) // disconnect to leave free the channel for the mobile app.
  .catch(console.log);
}
```

thank you!
