### ISSUE TITLE
Firmware 3.2.40 no Pos Data

### ISSUE THREAD

**Issue by mroschk** [koalazak/dorita980#86]
Hello,
i have a Roomba 600 series wit Firmware 3.2.40 but get no Position Data for the cleaning Map. 
Can you please help ??

Here is the Output from getMission:

{ cleanMissionStatus:
   { cycle: 'none',
     phase: 'stop',
     expireM: 0,
     rechrgM: 0,
     error: 0,
     notReady: 0,
     mssnM: 0,
     sqft: 0,
     initiator: '',
     nMssn: 20 },
  pose: undefined,
  bin: { present: true, full: false } }

Thanks a lot !!
Matthias

**Comment by koalazak** [comment]
Hey @mroschk, 
600 series robots are not reporting the position so you can't get that data.  You can check your robot capabilities calling `getRobotState()` method and looking for `cap` propertie.
A robot with map feature looks like:
```
"cap": {
 "pose":1,
 "ota":2,
 "multiPass":2,
 "carpetBoost":1
}
``` 

`pose` is for "position". This robot has the position feature.

we can not do anything if your robot does not report its position :/
