### ISSUE TITLE
New firmware 3.3.43-73

### ISSUE THREAD

**Issue by MarkyMarc35** [koalazak/dorita980#90]
Hi,
I just got my roomba (671 wifi) and it has firmeware 3.3.43-73.
When i run the app to get the password, i don't get any data back and only a connection error is displayed. The roomba is turn on and it did make a sound when i pressed the home button for a few second and the wifi indicator does flash.

**Comment by koalazak** [comment]
Hi @MarkyMarc35,

can you run this code and share the output please?

```
var dorita980 = require('dorita980');

dorita980.discovery((ierr, data) => {
  console.log(data);
});
```

thank you

**Comment by koalazak** [comment]
seems like you have the mobile app open, Please close it and try again.
Or maybe you have a firewall blocking port 8883 on your roomba.

**Comment by MarkyMarc35** [comment]
Turned off my phone to make sure the mobile app wasn't a factor, turned off my firewall as well and i get the same result.

**Comment by koalazak** [comment]
can you `nmap` your robot ip?
