### ISSUE TITLE
vacuumBar - wrapper for dorita980 for Mac

### ISSUE THREAD

**Issue by zachfeldman** [koalazak/dorita980#97]
Thought you might enjoy my wrapper of this lib to be used in the menu bar!
https://github.com/zachfeldman/vacuumBar

**Comment by koalazak** [comment]
awesome! thaks for sharing!

**Comment by zachfeldman** [comment]
You're welcome feel free to close or leave open! Or maybe I can make a pr into the Readme if you'd like?
